[package]
name = "photosort"
version = "0.1.0"
authors = ["Adam Zaiter <zaiter.adam7@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fs_extra = "1.1.0"
